import type { Locale } from "@/i18n/config";

export type LegalSection={id:string;title:string;paragraphs:string[];bullets?:string[]};
export type LegalPageContent={eyebrow:string;title:string;intro:string;lastUpdated:string;toc:string;contact:string;sections:LegalSection[]};
const updated={ar:"آخر تحديث: 14 أغسطس 2026",fr:"Dernière mise à jour : 14 août 2026",en:"Last updated: August 14, 2026"};

export const privacyContent:Record<Locale,LegalPageContent>={
 ar:{eyebrow:"الخصوصية والثقة",title:"سياسة الخصوصية",intro:"توضح هذه السياسة كيف تجمع منصة Estichara.ma بياناتك وتستخدمها وتحميها عندما تنشئ حسابًا أو تطرح سؤالًا أو تشتري توكن أو تتواصل مع الإدارة.",lastUpdated:updated.ar,toc:"محتويات السياسة",contact:"لأسئلة الخصوصية أو طلبات البيانات: support@estichara.ma",sections:[
  {id:"controller",title:"1. من المسؤول عن بياناتك؟",paragraphs:["Estichara.ma هي الجهة المسؤولة عن معالجة البيانات المرتبطة باستخدام المنصة. يمكنك التواصل معنا عبر support@estichara.ma بخصوص الخصوصية أو الوصول إلى بياناتك أو تصحيحها أو حذفها."]},
  {id:"collected",title:"2. البيانات التي نجمعها",paragraphs:["نجمع فقط البيانات اللازمة لتشغيل سوق الأسئلة والأجوبة وحماية المستخدمين."],bullets:["بيانات الحساب: الاسم، البريد الإلكتروني، الصورة، الهاتف والمدينة عند تقديمها.","بيانات Google: الاسم والبريد والصورة التي تسمح بمشاركتها عند تسجيل الدخول؛ لا نحصل على كلمة مرور Google.","المحتوى: الأسئلة والأجوبة والتقييمات والبلاغات ورسائل الدعم.","المعاملات: رصيد التوكن والطلبات وعمليات الفتح والمكافآت والسحوبات ومراجع الدفع.","البيانات التقنية: عنوان IP التقريبي، نوع المتصفح، الجهاز، سجلات الأمان والجلسات والأخطاء.","وثائق الخبراء: الهوية والسيرة والدبلومات والتراخيص المقدمة لغرض التحقق."]},
  {id:"use",title:"3. كيف نستخدم البيانات",paragraphs:["نستخدم البيانات لتقديم الخدمة، وليس لبيع معلوماتك الشخصية."],bullets:["إنشاء الحساب والمصادقة ومنع الاحتيال.","نشر المحتوى وإيصاله إلى الخبراء المؤهلين.","إدارة التوكن والمدفوعات والمكافآت والسحوبات.","التحقق من الخبراء ومراجعة المحتوى وحل النزاعات.","إرسال إشعارات الخدمة والرد على طلبات الدعم.","تحسين الأداء وقياس الاستخدام وتأمين المنصة.","الامتثال للالتزامات القانونية والطلبات النظامية الصحيحة."]},
  {id:"legal",title:"4. الأساس القانوني",paragraphs:["نعالج البيانات لتنفيذ عقد الخدمة معك، وبناءً على موافقتك عند الحاجة، ولحماية المصالح المشروعة مثل أمن المنصة ومنع الإساءة، وللامتثال للقانون المغربي المعمول به، بما فيه قواعد حماية البيانات ذات الصلة."]},
  {id:"providers",title:"5. مزودو الخدمة ونقل البيانات",paragraphs:["نعتمد على مزودين تقنيين لتشغيل المنصة، وقد تتم معالجة بعض البيانات في بلدان أخرى وفق ضماناتهم وشروطهم."],bullets:["Supabase: قاعدة البيانات والمصادقة والتخزين.","Netlify: استضافة الموقع ونشره.","Google: تسجيل الدخول الاختياري عبر Google OAuth.","Hostinger Email: البريد المهني عند استخدامه.","مزودو الدفع أو التحويل الذين تختارهم لإتمام المعاملة."]},
  {id:"sharing",title:"6. متى نشارك البيانات؟",paragraphs:["لا نبيع بياناتك. نشارك القدر الضروري مع مزودي الخدمة، أو بين المستخدم والخبير لتنفيذ الخدمة، أو مع السلطات عند وجود طلب قانوني ملزم. الأسئلة العامة والإجابات المعتمدة ومعلومات الملف المهني قد تكون ظاهرة للعموم وفق إعدادات المنصة."]},
  {id:"retention",title:"7. مدة الاحتفاظ والحذف",paragraphs:["نحتفظ بالبيانات ما دام الحساب نشطًا وبالمدة اللازمة للمحاسبة والأمان وتسوية النزاعات. يمكن حذف رسائل الدعم المغلقة من الإدارة. بعض سجلات المعاملات أو المراجعة قد تُحتفظ بها عند وجود التزام قانوني أو حاجة أمنية مشروعة."],bullets:["لطلب حذف الحساب، تواصل مع الإدارة من مركز الرسائل أو عبر support@estichara.ma.","حذف الحساب يزيل المحتوى والرسائل والمعاملات المرتبطة وفق قواعد قاعدة البيانات، مع الاستثناءات القانونية الضرورية."]},
  {id:"rights",title:"8. حقوقك",paragraphs:["بحسب القانون المطبق، يمكنك طلب الوصول إلى بياناتك وتصحيحها أو حذفها أو تقييد معالجتها أو الاعتراض عليها، وسحب الموافقة عندما تكون هي الأساس. قد نطلب التحقق من هويتك قبل تنفيذ الطلب."]},
  {id:"security",title:"9. الأمان وملفات الارتباط",paragraphs:["نستخدم صلاحيات قاعدة البيانات، تشفير الاتصال، سجلات التدقيق، وضوابط وصول لحماية البيانات. لا توجد وسيلة إلكترونية آمنة بنسبة مئة في المئة. نستخدم ملفات ارتباط أو تخزينًا محليًا ضروريًا للجلسة واللغة والمظهر والأمان؛ وقد نطلب موافقة منفصلة قبل أي تحليلات غير ضرورية."]},
  {id:"children",title:"10. القاصرون والتغييرات",paragraphs:["المنصة ليست موجهة للأطفال دون السن القانونية للتعاقد دون إشراف وليهم. قد نحدّث هذه السياسة عند تغير الخدمة أو القانون، وسننشر التاريخ الجديد ونرسل إشعارًا عند التغييرات المهمة."]}
 ]},
 fr:{eyebrow:"Confidentialité et confiance",title:"Politique de confidentialité",intro:"Cette politique explique comment Estichara.ma collecte, utilise et protège vos données lorsque vous créez un compte, posez une question, achetez des jetons ou contactez l’administration.",lastUpdated:updated.fr,toc:"Sommaire",contact:"Questions et demandes relatives aux données : support@estichara.ma",sections:[
  {id:"controller",title:"1. Responsable du traitement",paragraphs:["Estichara.ma est responsable des données traitées dans le cadre de la plateforme. Contactez support@estichara.ma pour toute demande d’accès, de rectification ou de suppression."]},
  {id:"collected",title:"2. Données collectées",paragraphs:["Nous collectons les données nécessaires au fonctionnement et à la sécurité du service."],bullets:["Compte : nom, e-mail, photo, téléphone et ville si fournis.","Connexion Google : nom, e-mail et photo autorisés ; nous ne recevons jamais votre mot de passe Google.","Contenu : questions, réponses, avis, signalements et messages d’assistance.","Transactions : solde, commandes, déblocages, récompenses, retraits et références de paiement.","Données techniques : appareil, navigateur, session, journaux de sécurité et erreurs.","Documents experts : identité, CV, diplômes et licences transmis pour vérification."]},
  {id:"use",title:"3. Utilisation des données",paragraphs:["Nous ne vendons pas vos données personnelles."],bullets:["Créer et sécuriser votre compte.","Acheminer les questions vers des experts qualifiés.","Gérer les jetons, paiements, récompenses et retraits.","Vérifier les experts et modérer le contenu.","Répondre aux demandes d’assistance et envoyer les notifications de service.","Améliorer les performances et prévenir les abus."]},
  {id:"legal",title:"4. Bases juridiques",paragraphs:["Le traitement repose sur l’exécution du service, votre consentement lorsque nécessaire, nos intérêts légitimes de sécurité et de prévention de la fraude, ainsi que les obligations légales applicables au Maroc."]},
  {id:"providers",title:"5. Prestataires et transferts",paragraphs:["Certains prestataires peuvent traiter des données dans d’autres pays selon leurs garanties contractuelles."],bullets:["Supabase : base de données, authentification et stockage.","Netlify : hébergement et déploiement.","Google : connexion OAuth facultative.","Hostinger Email : messagerie professionnelle.","Prestataires de paiement ou de transfert choisis."]},
  {id:"sharing",title:"6. Partage",paragraphs:["Nous partageons uniquement les données nécessaires avec nos prestataires, les participants à une consultation ou les autorités disposant d’une demande légalement valable. Les questions publiques, réponses approuvées et profils professionnels peuvent être visibles publiquement."]},
  {id:"retention",title:"7. Conservation et suppression",paragraphs:["Les données sont conservées pendant la vie du compte et aussi longtemps que nécessaire pour la comptabilité, la sécurité et les litiges. Certaines traces peuvent être conservées lorsque la loi ou un intérêt de sécurité légitime l’exige."],bullets:["Demandez la suppression depuis le centre d’assistance ou à support@estichara.ma.","La suppression du compte efface les données associées sous réserve des obligations légales."]},
  {id:"rights",title:"8. Vos droits",paragraphs:["Selon la loi applicable, vous pouvez demander l’accès, la rectification, la suppression, la limitation ou l’opposition, et retirer votre consentement. Une vérification d’identité peut être demandée."]},
  {id:"security",title:"9. Sécurité et cookies",paragraphs:["Nous utilisons des règles d’accès, des connexions chiffrées et des journaux d’audit. Aucun système n’est totalement exempt de risque. Le stockage local et les cookies nécessaires servent à la session, la langue, le thème et la sécurité."]},
  {id:"children",title:"10. Mineurs et mises à jour",paragraphs:["Le service n’est pas destiné aux mineurs ne pouvant pas contracter sans représentant légal. Toute modification importante de cette politique sera signalée sur la plateforme."]}
 ]},
 en:{eyebrow:"Privacy and trust",title:"Privacy Policy",intro:"This policy explains how Estichara.ma collects, uses and protects information when you create an account, ask a question, purchase tokens or contact administration.",lastUpdated:updated.en,toc:"Contents",contact:"Privacy and data requests: support@estichara.ma",sections:[
  {id:"controller",title:"1. Who controls your data?",paragraphs:["Estichara.ma controls personal data processed through the platform. Contact support@estichara.ma to request access, correction or deletion."]},
  {id:"collected",title:"2. Information we collect",paragraphs:["We collect information needed to operate and secure the service."],bullets:["Account details: name, email, profile image, phone and city when provided.","Google sign-in: the name, email and image you authorize; we never receive your Google password.","Content: questions, answers, reviews, reports and support messages.","Transactions: token balance, orders, unlocks, rewards, withdrawals and payment references.","Technical data: browser, device, sessions, security logs and errors.","Expert documents: identity, résumé, diplomas and licences submitted for verification."]},
  {id:"use",title:"3. How we use information",paragraphs:["We do not sell your personal information."],bullets:["Create, authenticate and protect accounts.","Route questions to qualified experts.","Operate token, payment, reward and withdrawal features.","Verify experts, moderate content and resolve disputes.","Provide support and service notifications.","Improve performance and prevent misuse.","Comply with valid legal obligations."]},
  {id:"legal",title:"4. Legal bases",paragraphs:["We process information to perform our agreement with you, with consent where required, for legitimate security and anti-fraud interests, and to comply with applicable Moroccan law."]},
  {id:"providers",title:"5. Providers and international processing",paragraphs:["Service providers may process information in other countries under their safeguards and terms."],bullets:["Supabase: database, authentication and storage.","Netlify: website hosting and deployment.","Google: optional OAuth sign-in.","Hostinger Email: professional email.","Payment or transfer providers you choose."]},
  {id:"sharing",title:"6. Sharing",paragraphs:["We share only what is necessary with providers, consultation participants, or authorities with a binding lawful request. Public questions, approved answers and professional profile information may be publicly visible."]},
  {id:"retention",title:"7. Retention and deletion",paragraphs:["We keep information while the account is active and as needed for accounting, security and dispute resolution. Certain records may be retained where required by law or a legitimate security need."],bullets:["Request account deletion through support or support@estichara.ma.","Account deletion removes associated information subject to necessary legal retention."]},
  {id:"rights",title:"8. Your rights",paragraphs:["Depending on applicable law, you may request access, correction, deletion, restriction or objection, and withdraw consent where consent is the basis. We may verify your identity first."]},
  {id:"security",title:"9. Security and cookies",paragraphs:["We use database access policies, encrypted connections, audit logs and access controls. No electronic system is completely risk-free. Necessary cookies or local storage support sessions, language, appearance and security."]},
  {id:"children",title:"10. Children and changes",paragraphs:["The service is not intended for children who cannot legally agree to these terms without a guardian. We may update this policy and will post a new date and notify users of material changes."]}
 ]}
};

export const termsContent:Record<Locale,LegalPageContent>={
 ar:{eyebrow:"القواعد القانونية",title:"شروط الاستخدام",intro:"تحكم هذه الشروط استخدامك لمنصة Estichara.ma، بما في ذلك الحسابات والأسئلة وإجابات الخبراء والتوكن والمدفوعات.",lastUpdated:updated.ar,toc:"محتويات الشروط",contact:"للاستفسارات القانونية: support@estichara.ma",sections:[
  {id:"acceptance",title:"1. قبول الشروط",paragraphs:["باستخدام المنصة أو إنشاء حساب، فإنك توافق على هذه الشروط وسياسة الخصوصية. إذا لم توافق، فلا تستخدم الخدمة."]},
  {id:"eligibility",title:"2. الأهلية والحساب",paragraphs:["يجب أن تكون قادرًا قانونيًا على إبرام عقد أو تستخدم المنصة بإشراف ولي قانوني. قدّم معلومات صحيحة، واحم كلمة مرورك، وأبلغنا عن أي استعمال غير مصرح به. أنت مسؤول عن النشاط الصادر من حسابك ما لم يكن سببه تقصيرًا من المنصة."]},
  {id:"service",title:"3. طبيعة الخدمة",paragraphs:["Estichara.ma سوق معرفي يربط المستخدمين بخبراء وأشخاص ذوي خبرة. لا نضمن أن كل إجابة كاملة أو مناسبة لكل حالة، ولا تشكّل المنصة بديلًا تلقائيًا عن استشارة قانونية أو طبية أو مالية شخصية."],bullets:["في الحالات الطبية الطارئة اتصل بخدمات الطوارئ أو بطبيب مؤهل فورًا.","تحقق من القرارات المهمة مع مهني مرخص يطّلع على تفاصيل حالتك ووثائقك."]},
  {id:"content",title:"4. الأسئلة والمحتوى",paragraphs:["تحتفظ بحقوق المحتوى الذي تنشئه، وتمنح المنصة ترخيصًا غير حصري لعرضه وتخزينه وترجمته تقنيًا وفهرسته وتشغيل الخدمة. لا تنشر بيانات حساسة لا تلزم للسؤال، أو محتوى لا تملك حق استعماله."]},
  {id:"experts",title:"5. التزامات الخبراء",paragraphs:["يجب على الخبراء تقديم معلومات صحيحة عن مؤهلاتهم، الإجابة ضمن تخصصهم، التصريح عن تضارب المصالح، واحترام السرية والقواعد المهنية. التوثيق لا يعني ضمان كل رأي أو نتيجة."]},
  {id:"tokens",title:"6. التوكن والمدفوعات",paragraphs:["التوكن وحدة استعمال داخل المنصة وليست عملة أو وديعة بنكية. تظهر الأسعار والمكافآت قبل التأكيد. لا تخصم المنصة التوكن مرتين لنفس عملية الفتح المسجلة."],bullets:["طلبات الشراء تخضع لتأكيد الدفع.","مكافأة السؤال تُحجز عند النشر المدفوع، وتُدفع وفق قواعد الإجابة المعتمدة أو تُسترجع عند الرفض أو الإلغاء المؤهل.","المبالغ المدفوعة وسياسة الاسترجاع تخضع للحالة والوسيلة والقانون المطبق.","سحوبات الخبراء تخضع للحد الأدنى والتحقق والمراجعة الإدارية."]},
  {id:"moderation",title:"7. المراجعة والإنفاذ",paragraphs:["يجوز لنا مراجعة المحتوى أو رفضه أو إغلاقه أو حذفه، وتعليق الحسابات أو حظرها عند مخالفة القواعد أو تهديد الأمان. نحاول توضيح الأسباب، ويمكن التواصل مع الإدارة للاعتراض."]},
  {id:"prohibited",title:"8. الاستخدام الممنوع",paragraphs:["يُمنع الاحتيال، انتحال الهوية، التحايل على التوكن، المضايقة، الرسائل المزعجة، نشر محتوى غير قانوني، جمع بيانات الآخرين دون إذن، محاولة اختراق الخدمة، أو استخدام المنصة لإيذاء الآخرين."]},
  {id:"ip",title:"9. الملكية الفكرية",paragraphs:["العلامة والتصميم والبرمجيات والمحتوى التحريري الخاص بالمنصة مملوك لأصحابه ومحمي بالقانون. لا يجوز نسخه أو إعادة بيعه أو الهندسة العكسية له إلا في الحدود التي يسمح بها القانون."]},
  {id:"availability",title:"10. التوفر والتغييرات",paragraphs:["قد نحدّث الخدمة أو نوقف ميزة مؤقتًا للصيانة أو الأمان. نسعى للاستمرارية لكننا لا نضمن توفرًا بلا انقطاع أو خلو الخدمة من كل خطأ."]},
  {id:"liability",title:"11. المسؤولية",paragraphs:["في الحدود التي يسمح بها القانون، لا تتحمل المنصة الخسائر غير المباشرة الناتجة عن الاعتماد غير المناسب على محتوى عام أو عن خدمات أطراف ثالثة. لا تستبعد هذه الشروط أي مسؤولية لا يسمح القانون باستبعادها."]},
  {id:"law",title:"12. القانون والتواصل",paragraphs:["تخضع هذه الشروط للقانون المغربي المعمول به. نسعى أولًا إلى حل النزاعات وديًا عبر support@estichara.ma أو مركز الدعم. قد نحدّث الشروط ونبلغ عن التغييرات الجوهرية؛ استمرار الاستخدام بعدها يعني قبول النسخة الجديدة ضمن ما يسمح به القانون."]}
 ]},
 fr:{eyebrow:"Règles juridiques",title:"Conditions d’utilisation",intro:"Ces conditions régissent l’utilisation d’Estichara.ma, notamment les comptes, questions, réponses d’experts, jetons et paiements.",lastUpdated:updated.fr,toc:"Sommaire",contact:"Questions juridiques : support@estichara.ma",sections:[
  {id:"acceptance",title:"1. Acceptation",paragraphs:["En utilisant la plateforme ou en créant un compte, vous acceptez ces conditions et la Politique de confidentialité."]},
  {id:"eligibility",title:"2. Éligibilité et compte",paragraphs:["Vous devez avoir la capacité juridique requise ou utiliser le service sous la supervision d’un représentant légal. Fournissez des informations exactes et protégez vos identifiants."]},
  {id:"service",title:"3. Nature du service",paragraphs:["Estichara.ma est une place de marché de connaissances. Les réponses générales ne remplacent pas automatiquement une consultation juridique, médicale ou financière adaptée à votre situation."],bullets:["En cas d’urgence médicale, contactez immédiatement les services d’urgence ou un professionnel qualifié.","Faites vérifier les décisions importantes par un professionnel ayant accès à votre dossier complet."]},
  {id:"content",title:"4. Contenu",paragraphs:["Vous conservez vos droits sur le contenu créé et accordez à la plateforme une licence non exclusive nécessaire à son stockage, affichage, indexation et fonctionnement. Ne publiez pas de données sensibles inutiles."]},
  {id:"experts",title:"5. Obligations des experts",paragraphs:["Les experts doivent présenter honnêtement leurs qualifications, répondre dans leur domaine, signaler les conflits d’intérêts et respecter les règles professionnelles."]},
  {id:"tokens",title:"6. Jetons et paiements",paragraphs:["Les jetons sont des unités d’usage internes, pas une monnaie ni un dépôt bancaire. Les coûts sont affichés avant confirmation."],bullets:["Les achats sont crédités après confirmation du paiement.","Les récompenses de question sont mises en réserve puis payées ou remboursées selon les règles affichées.","Les retraits sont soumis au minimum, aux contrôles et à l’approbation."]},
  {id:"moderation",title:"7. Modération",paragraphs:["Nous pouvons examiner, refuser, fermer ou supprimer du contenu, et suspendre les comptes qui enfreignent les règles ou menacent la sécurité."]},
  {id:"prohibited",title:"8. Usages interdits",paragraphs:["Sont interdits : fraude, usurpation, contournement des jetons, harcèlement, spam, contenu illégal, collecte non autorisée de données et tentatives d’intrusion."]},
  {id:"ip",title:"9. Propriété intellectuelle",paragraphs:["La marque, le design, le logiciel et le contenu éditorial appartiennent à leurs titulaires et ne peuvent être copiés ou revendus sans autorisation."]},
  {id:"availability",title:"10. Disponibilité",paragraphs:["Le service peut être modifié ou temporairement interrompu pour maintenance ou sécurité. Une disponibilité sans interruption n’est pas garantie."]},
  {id:"liability",title:"11. Responsabilité",paragraphs:["Dans les limites légales, la plateforme n’est pas responsable des pertes indirectes résultant d’un usage inapproprié d’informations générales ou de services tiers."]},
  {id:"law",title:"12. Droit applicable",paragraphs:["Ces conditions sont régies par le droit marocain applicable. Contactez support@estichara.ma pour rechercher une solution amiable. Les modifications importantes seront signalées."]}
 ]},
 en:{eyebrow:"Legal rules",title:"Terms of Service",intro:"These terms govern your use of Estichara.ma, including accounts, questions, expert answers, tokens and payments.",lastUpdated:updated.en,toc:"Contents",contact:"Legal questions: support@estichara.ma",sections:[
  {id:"acceptance",title:"1. Acceptance",paragraphs:["By using the platform or creating an account, you agree to these Terms and the Privacy Policy. If you do not agree, do not use the service."]},
  {id:"eligibility",title:"2. Eligibility and accounts",paragraphs:["You must be legally able to enter an agreement or use the service with a legal guardian. Provide accurate information, protect your credentials and report unauthorized access."]},
  {id:"service",title:"3. Nature of the service",paragraphs:["Estichara.ma is a knowledge marketplace connecting users with experts and experienced contributors. General answers do not automatically replace legal, medical or financial advice tailored to your circumstances."],bullets:["For a medical emergency, contact emergency services or a qualified professional immediately.","Have important decisions reviewed by a licensed professional with access to your complete facts and documents."]},
  {id:"content",title:"4. User content",paragraphs:["You retain rights in content you create and grant the platform a non-exclusive licence needed to store, display, index and operate it. Do not publish unnecessary sensitive data or content you have no right to use."]},
  {id:"experts",title:"5. Expert obligations",paragraphs:["Experts must accurately represent qualifications, answer within their competence, disclose conflicts and follow confidentiality and professional rules. Verification does not guarantee every opinion or outcome."]},
  {id:"tokens",title:"6. Tokens and payments",paragraphs:["Tokens are internal service units, not currency or a bank deposit. Prices and rewards are shown before confirmation."],bullets:["Purchases are credited after payment confirmation.","Question rewards are held and then paid or refunded under the displayed rules.","Refund eligibility depends on status, payment method and applicable law.","Expert withdrawals are subject to minimums, verification and review."]},
  {id:"moderation",title:"7. Moderation and enforcement",paragraphs:["We may review, reject, close or remove content and suspend accounts that violate rules or threaten safety. Users may contact administration to appeal."]},
  {id:"prohibited",title:"8. Prohibited use",paragraphs:["Fraud, impersonation, token circumvention, harassment, spam, unlawful content, unauthorized data collection, intrusion attempts and harmful use are prohibited."]},
  {id:"ip",title:"9. Intellectual property",paragraphs:["The platform brand, design, software and editorial content belong to their owners and may not be copied, resold or reverse engineered except where law permits."]},
  {id:"availability",title:"10. Availability and changes",paragraphs:["We may update or temporarily suspend features for maintenance or safety. We do not promise uninterrupted or error-free availability."]},
  {id:"liability",title:"11. Liability",paragraphs:["To the extent permitted by law, the platform is not responsible for indirect loss caused by inappropriate reliance on general content or third-party services. Nothing excludes liability that cannot legally be excluded."]},
  {id:"law",title:"12. Governing law and contact",paragraphs:["These terms are governed by applicable Moroccan law. Contact support@estichara.ma first to seek an amicable solution. Material changes will be communicated as appropriate."]}
 ]}
};
