import { useEffect,useState } from "react";
import { createFileRoute,Link } from "@tanstack/react-router";
import { BadgeCheck,Loader2,MessageSquare,Star } from "lucide-react";
import { SiteLayout } from "@/components/site/layout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { usePageCopy } from "@/i18n/page-copy";
import { formatDate,formatNumber } from "@/i18n/format";
import { useLocale } from "@/i18n/use-locale";
import { supabase } from "@/lib/supabase";
import { useSiteSettings } from "@/lib/site-settings";

type Review={id:string;rating:number;comment:string;created_at:string;reviewer_name:string};type Answer={id:string;preview:string;created_at:string;question_title:string;question_slug:string};type Profile={user_id:string;slug:string;full_name:string;avatar_url:string|null;title:string;specialization:string;bio:string;city:string;verified:boolean;rating:number;reviews_count:number;answered_count:number;audience_ids:string[];reviews:Review[];answers:Answer[]};
export const Route=createFileRoute("/experts/$expertSlug")({component:ExpertProfile,head:()=>({meta:[{title:"Expert — Estichara.ma"}]})});
function ExpertProfile(){const{expertSlug}=Route.useParams();const copy=usePageCopy().expert;const locale=useLocale();const site=useSiteSettings();const[profile,setProfile]=useState<Profile|null>(null);const[loading,setLoading]=useState(true);
 useEffect(()=>{supabase.rpc("get_public_expert_profile",{p_ref:expertSlug}).then(({data})=>{setProfile(data as Profile|null);setLoading(false)})},[expertSlug]);
 if(site.loaded&&site.features["expert_applications"]===false)return <SiteLayout><div className="mx-auto max-w-xl px-4 py-32 text-center"><h1 className="text-3xl font-semibold">دليل الخبراء غير متاح حاليًا.</h1></div></SiteLayout>;
 if(loading)return <SiteLayout><div className="grid min-h-[55vh] place-items-center"><Loader2 className="size-8 animate-spin text-primary"/></div></SiteLayout>;
 if(!profile)return <SiteLayout><div className="mx-auto max-w-xl px-4 py-32 text-center"><h1 className="text-3xl font-semibold">{copy.notFound}</h1><Button asChild className="mt-6"><Link to="/experts">{copy.back}</Link></Button></div></SiteLayout>;
 const initials=profile.full_name.split(" ").map(x=>x[0]).slice(0,2).join("");return <SiteLayout><section className="bg-hero border-b border-border/60"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-4 py-14 sm:flex-row sm:items-center sm:px-6 sm:py-20">{profile.avatar_url?<img src={profile.avatar_url} alt={profile.full_name} className="size-24 rounded-[2rem] object-cover shadow-lift"/>:<span className="bg-brand grid size-24 place-items-center rounded-[2rem] text-3xl font-semibold text-primary-foreground shadow-lift">{initials}</span>}<div><div className="flex flex-wrap items-center gap-2"><h1 className="text-3xl font-semibold sm:text-5xl">{profile.full_name}</h1>{profile.verified&&<Badge className="rounded-full bg-secondary"><BadgeCheck className="size-3.5"/>{copy.verifiedLevel}</Badge>}</div><p className="mt-2 text-muted-foreground">{profile.title}{profile.specialization?` · ${profile.specialization}`:""}{profile.city?` · ${profile.city}`:""}</p></div></div></section><section className="mx-auto max-w-7xl px-4 py-12 sm:px-6"><div className="grid grid-cols-3 gap-3"><Stat label={copy.rating} value={`${Number(profile.rating)||0}/5`}/><Stat label={copy.answersDelivered} value={formatNumber(profile.answered_count,locale)}/><Stat label={copy.reviews} value={formatNumber(profile.reviews_count,locale)}/></div><div className="mt-12 grid gap-10 lg:grid-cols-[1fr_340px]"><div><h2 className="text-2xl font-semibold">{copy.biography}</h2><p className="mt-4 whitespace-pre-line text-sm leading-7 text-muted-foreground">{profile.bio||"—"}</p><h2 className="mt-12 text-2xl font-semibold">{copy.recentAnswers}</h2><div className="mt-5 space-y-3">{profile.answers?.map(answer=><Link key={answer.id} to="/questions/$questionId" params={{questionId:answer.question_slug}} className="premium-card block p-5 transition hover:border-primary/30"><h3 className="font-semibold">{answer.question_title}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-muted-foreground">{answer.preview}</p></Link>)}{!profile.answers?.length&&<p className="text-sm text-muted-foreground">No published answers yet.</p>}</div></div><aside><h2 className="text-xl font-semibold">{copy.reviews}</h2><div className="mt-4 space-y-3">{profile.reviews?.map(review=><article key={review.id} className="premium-card p-4"><div className="flex gap-0.5">{[1,2,3,4,5].map(i=><Star key={i} className={`size-3.5 ${i<=review.rating?"fill-accent text-accent":"text-muted"}`}/>)}</div>{review.comment&&<p className="mt-2 text-sm leading-6 text-muted-foreground">{review.comment}</p>}<p className="mt-2 text-[10px] text-muted-foreground">{review.reviewer_name} · {formatDate(review.created_at,locale)}</p></article>)}{!profile.reviews?.length&&<p className="text-sm text-muted-foreground">No reviews yet.</p>}</div></aside></div></section></SiteLayout>}
function Stat({label,value}:{label:string;value:string}){return <article className="premium-card p-5"><p className="text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></article>}
