
import { useEffect,useState } from "react";
import { createFileRoute,Link,useNavigate } from "@tanstack/react-router";
import { ArrowDownLeft,ArrowUpRight,Coins,Copy,Gift,History,Loader2,Share2,WalletCards } from "lucide-react";
import { toast } from "sonner";
import { SiteLayout,PageHeader } from "@/components/site/layout";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useAuth } from "@/lib/auth";
import { useSiteSettings } from "@/lib/site-settings";
import { supabase } from "@/lib/supabase";
import { useLocale } from "@/i18n/use-locale";

export const Route=createFileRoute("/wallet")({component:WalletPage});
type Tx={id:string;amount:number;type:string;note:string;created_at:string};
const LABELS:Record<string,{ar:string;fr:string;en:string}>={signup_bonus:{ar:"مكافأة إنشاء الحساب",fr:"Bonus d’inscription",en:"Welcome bonus"},share_bonus:{ar:"مكافأة مشاركة الموقع",fr:"Bonus de partage",en:"Share reward"},earn_answer:{ar:"مكافأة أفضل إجابة",fr:"Récompense de la meilleure réponse",en:"Best answer reward"},earn_question_reward:{ar:"مكافأة سؤال",fr:"Récompense de question",en:"Question reward"},earn_bonus:{ar:"مكافأة إضافية",fr:"Bonus supplémentaire",en:"Extra bonus"},admin_adjust:{ar:"تعديل من الإدارة",fr:"Ajustement administratif",en:"Admin adjustment"},purchase:{ar:"شراء توكن",fr:"Achat de jetons",en:"Token purchase"},spend_unlock:{ar:"فتح إجابة",fr:"Déblocage d’une réponse",en:"Answer unlock"},spend_question:{ar:"مكافأة سؤال محجوزة",fr:"Récompense de question",en:"Question reward held"},refund_question:{ar:"استرجاع مكافأة سؤال",fr:"Remboursement",en:"Question refund"},withdrawal_hold:{ar:"طلب تحويل",fr:"Demande de retrait",en:"Withdrawal request"},withdrawal_refund:{ar:"استرجاع طلب تحويل",fr:"Remboursement du retrait",en:"Withdrawal refund"}};
function WalletPage(){
 const{user,profile,loading,refreshProfile}=useAuth();const site=useSiteSettings();const locale=useLocale();const navigate=useNavigate();const[txs,setTxs]=useState<Tx[]>([]);const[rate,setRate]=useState(.5);const[busy,setBusy]=useState(false);
 async function load(){if(!user)return;const[{data},{data:setting}]=await Promise.all([supabase.from("token_transactions").select("id,amount,type,note,created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(100),supabase.from("settings").select("value").eq("key","token_to_mad").single()]);setTxs((data as Tx[])??[]);setRate(Number(setting?.value)||.5)}
 useEffect(()=>{if(!loading&&!user)navigate({to:"/auth"});if(user)load()},[user?.id,loading]);
 async function rewardShare(channel:string){if(!user||busy)return;setBusy(true);const url=`https://estichara.ma/${locale}`;try{if(channel==="native"&&navigator.share)await navigator.share({title:"Estichara.ma",text:locale==="ar"?"اكتشف إجابات موثوقة من خبراء حقيقيين":"Discover trusted answers from verified experts",url});else if(channel==="whatsapp")window.open(`https://wa.me/?text=${encodeURIComponent(`Estichara.ma — ${url}`)}`,"_blank");else{await navigator.clipboard.writeText(url);toast.success(locale==="ar"?"تم نسخ الرابط":"Link copied")}
 const{error}=await supabase.rpc("claim_share_reward",{p_channel:channel});if(error){if(error.message.includes("SHARE_DAILY_LIMIT"))toast.info(locale==="ar"?"حصلت على مكافأة المشاركة اليومية بالفعل":"Daily share reward already claimed");else toast.error(error.message)}else{await refreshProfile();await load();toast.success(locale==="ar"?`حصلت على ${site.tokenProgram.share_bonus} توكن`: `+${site.tokenProgram.share_bonus} tokens`)}}catch{}finally{setBusy(false)}}
 if(loading||!user)return <SiteLayout><div className="grid min-h-[50vh] place-items-center"><Loader2 className="size-8 animate-spin text-primary"/></div></SiteLayout>;
 if(site.loaded&&(site.tokenProgram.mode==="hidden"||!site.tokenProgram.wallet_enabled))return <SiteLayout><div className="mx-auto max-w-lg px-4 py-32 text-center"><WalletCards className="mx-auto size-12 text-muted-foreground"/><h1 className="mt-5 text-3xl font-semibold">{locale==="ar"?"المحفظة مخفية حاليًا":"Wallet is currently unavailable"}</h1><Button asChild className="mt-6 rounded-xl"><Link to="/account">{locale==="ar"?"العودة إلى الحساب":"Back to account"}</Link></Button></div></SiteLayout>;
 const balance=profile?.tokens_balance??0;const mad=balance*rate;
 return <SiteLayout><PageHeader eyebrow={locale==="ar"?"محفظتي":locale==="fr"?"Mon portefeuille":"My wallet"} title={locale==="ar"?"التوكن والمكافآت":locale==="fr"?"Jetons et récompenses":"Tokens and rewards"} description={locale==="ar"?"تابع رصيدك واعرف من أين حصلت على كل توكن.":locale==="fr"?"Suivez votre solde et l’origine de chaque récompense.":"Track your balance and where every reward came from."}/><section className="mx-auto max-w-5xl px-4 py-12 sm:px-6 sm:py-16"><div className="grid gap-5 lg:grid-cols-[1fr_.75fr]"><div className="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-primary to-secondary p-7 text-primary-foreground shadow-2xl shadow-primary/15"><div className="absolute -end-16 -top-20 size-56 rounded-full bg-white/10 blur-3xl"/><p className="flex items-center gap-2 text-sm text-primary-foreground/65"><Coins className="size-4"/>{locale==="ar"?"الرصيد الحالي":"Current balance"}</p><p className="mt-4 text-5xl font-bold">{balance.toLocaleString()} <span className="text-base font-normal text-primary-foreground/60">tokens</span></p><div className="mt-6 inline-flex rounded-2xl border border-white/15 bg-white/10 px-4 py-3"><div><p className="text-[10px] text-primary-foreground/55">{locale==="ar"?"القيمة التقديرية بالدرهم":"Estimated value in MAD"}</p><p className="mt-1 text-2xl font-bold text-accent">{mad.toLocaleString(undefined,{maximumFractionDigits:2})} MAD</p></div></div><p className="mt-4 text-[10px] leading-5 text-primary-foreground/50">1 token = {rate} MAD · {locale==="ar"?"القيمة يحددها مدير المنصة":"Rate configured by administration"}</p></div><div className="premium-card p-6"><div className="flex items-center gap-2"><Gift className="size-5 text-accent"/><h2 className="font-semibold">{locale==="ar"?"اربح توكن بالمشاركة":"Earn by sharing"}</h2></div><p className="mt-2 text-xs leading-6 text-muted-foreground">{locale==="ar"?`شارك Estichara.ma واحصل على ${site.tokenProgram.share_bonus} توكن، بحد أقصى ${site.tokenProgram.share_daily_limit} مرة يوميًا.`:"Share Estichara.ma and receive a reward."}</p><div className="mt-4 grid grid-cols-3 gap-2"><Button variant="outline" size="sm" disabled={busy} onClick={()=>rewardShare("whatsapp")} className="rounded-xl">WhatsApp</Button><Button variant="outline" size="sm" disabled={busy} onClick={()=>rewardShare("copy")} className="rounded-xl"><Copy className="size-3.5"/>{locale==="ar"?"نسخ":"Copy"}</Button><Button size="sm" disabled={busy} onClick={()=>rewardShare("native")} className="rounded-xl"><Share2 className="size-3.5"/>{locale==="ar"?"مشاركة":"Share"}</Button></div></div></div>
 <div className="mt-8 premium-card overflow-hidden"><div className="flex items-center justify-between border-b border-border/60 p-5 sm:p-6"><div><h2 className="flex items-center gap-2 text-lg font-semibold"><History className="size-5 text-primary"/>{locale==="ar"?"سجل التوكن":"Token history"}</h2><p className="mt-1 text-xs text-muted-foreground">{locale==="ar"?"كل المكافآت والحركات في حسابك":"All rewards and movements"}</p></div><Badge variant="outline" className="rounded-full">{txs.length}</Badge></div><div className="divide-y divide-border/55">{txs.map(tx=>{const positive=tx.amount>0;const label=LABELS[tx.type]?.[locale]??tx.type;return <div key={tx.id} className="flex items-center gap-4 p-4 sm:px-6"><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${positive?"bg-emerald-50 text-emerald-600":"bg-rose-50 text-rose-600"}`}>{positive?<ArrowDownLeft className="size-4"/>:<ArrowUpRight className="size-4"/>}</span><div className="min-w-0 flex-1"><p className="text-sm font-medium">{label}</p><p className="mt-1 truncate text-[10px] text-muted-foreground">{tx.note||new Date(tx.created_at).toLocaleString()}</p></div><div className="text-end"><p dir="ltr" className={`font-bold ${positive?"text-emerald-600":"text-rose-600"}`}>{positive?"+":""}{tx.amount}</p><p className="text-[9px] text-muted-foreground">{(tx.amount*rate).toFixed(2)} MAD</p></div></div>})}{txs.length===0&&<div className="py-16 text-center text-sm text-muted-foreground">{locale==="ar"?"لا توجد حركات بعد":"No activity yet"}</div>}</div></div></section></SiteLayout>
}
