import { useEffect, useState } from "react";
import { Package, Plus, Pencil, Eye, EyeOff, X, Save, Star, BadgePercent } from "lucide-react";
import { supabase } from "../supabase";
import { Card, Badge, Btn, Empty } from "../ui";

type Pack={id:string;name_ar:string;name_fr:string;name_en:string;tokens:number;bonus:number;price_mad:number;promo_price_mad:number|null;promo_ends_at:string|null;popular:boolean;active:boolean;sort:number};
const EMPTY:Omit<Pack,"id">={name_ar:"",name_fr:"",name_en:"",tokens:100,bonus:0,price_mad:99,promo_price_mad:null,promo_ends_at:null,popular:false,active:true,sort:1};
export function TokenPacksPage(){
 const[rows,setRows]=useState<Pack[]>([]);const[editing,setEditing]=useState<Pack|null>(null);const[saving,setSaving]=useState(false);
 async function load(){const{data,error}=await supabase.from("token_packs").select("id,name_ar,name_fr,name_en,tokens,bonus,price_mad,promo_price_mad,promo_ends_at,popular,active,sort").order("sort");if(error){alert(`${error.message}\nشغّل migration 09 أولًا.`);return}setRows((data as Pack[])??[])}
 useEffect(()=>{load()},[]);
 function add(){setEditing({id:"",...EMPTY,sort:rows.length+1})}
 async function save(){if(!editing||!editing.name_ar.trim()||editing.tokens<=0||editing.price_mad<0){alert("تحقق من اسم الباقة والعدد والسعر");return}setSaving(true);const{id,...values}=editing;const payload={...values,promo_price_mad:values.promo_price_mad||null,promo_ends_at:values.promo_ends_at||null};const{error}=id?await supabase.from("token_packs").update(payload).eq("id",id):await supabase.from("token_packs").insert(payload);setSaving(false);if(error){alert(error.message);return}setEditing(null);load()}
 async function toggle(p:Pack){await supabase.from("token_packs").update({active:!p.active}).eq("id",p.id);load()}
 function effective(p:Pack){return p.promo_price_mad!==null&&(!p.promo_ends_at||new Date(p.promo_ends_at)>new Date())?p.promo_price_mad:p.price_mad}
 return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><Package className="size-6 text-brand-teal"/> باقات التوكن</h1><p className="mt-1 text-sm text-ink/55">تحكم كامل في الأسعار والترجمات والعروض والترتيب</p></div><Btn onClick={add}><Plus className="size-4"/> باقة جديدة</Btn></div>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{rows.map(p=><Card key={p.id} className={`relative overflow-hidden p-5 transition hover:-translate-y-1 hover:shadow-lg ${!p.active?"opacity-50":""} ${p.popular?"border-brand-gold/50":""}`}>{p.popular&&<span className="absolute end-0 top-0 rounded-bl-xl bg-brand-gold px-3 py-1 text-[10px] font-bold text-brand-dark">الأكثر شيوعًا</span>}<div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-xl bg-brand-teal/10 text-brand-teal"><Package className="size-4.5"/></span>{p.active?<Badge tone="success">متاحة</Badge>:<Badge>مخفية</Badge>}</div><h2 className="mt-4 font-bold">{p.name_ar}</h2><p className="mt-2 text-3xl font-bold text-brand-dark">{p.tokens.toLocaleString("ar-MA")}</p><p className="text-xs text-ink/40">توكن {p.bonus>0&&<span className="text-brand-teal">+ {p.bonus} بونص</span>}</p><div className="mt-4 flex items-baseline gap-2">{effective(p)!==p.price_mad&&<span className="text-xs text-ink/35 line-through">{p.price_mad}</span>}<b className="text-xl">{effective(p)} د.م</b></div>{effective(p)!==p.price_mad&&<p className="mt-1 flex items-center gap-1 text-[10px] text-rose-600"><BadgePercent className="size-3"/> عرض إلى {p.promo_ends_at?new Date(p.promo_ends_at).toLocaleDateString("ar-MA"):"إشعار آخر"}</p>}<div className="mt-4 flex gap-2 border-t border-ink/7 pt-3"><Btn small tone="ghost" onClick={()=>setEditing({...p})}><Pencil className="size-3.5"/> تعديل</Btn><Btn small tone={p.active?"danger":"primary"} onClick={()=>toggle(p)}>{p.active?<EyeOff className="size-3.5"/>:<Eye className="size-3.5"/>}{p.active?"إخفاء":"إظهار"}</Btn></div></Card>)}{rows.length===0&&<Card className="sm:col-span-2 xl:col-span-4"><Empty text="لا توجد باقات"/></Card>}</div>
 {editing&&<div className="fixed inset-0 z-50 flex justify-end bg-ink/30 backdrop-blur-sm" onMouseDown={e=>e.target===e.currentTarget&&setEditing(null)}><div className="h-full w-full max-w-xl overflow-y-auto bg-paper p-6 shadow-2xl sm:p-8"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">{editing.id?"تعديل باقة":"باقة جديدة"}</h2><p className="mt-1 text-xs text-ink/45">ستظهر التغييرات مباشرة في متجر التوكن</p></div><button onClick={()=>setEditing(null)} className="rounded-xl bg-ink/5 p-2"><X className="size-5"/></button></div><div className="mt-7 space-y-4"><Field label="الاسم بالعربية" value={editing.name_ar} onChange={v=>setEditing({...editing,name_ar:v})}/><Field label="Nom français" value={editing.name_fr} dir="ltr" onChange={v=>setEditing({...editing,name_fr:v})}/><Field label="English name" value={editing.name_en} dir="ltr" onChange={v=>setEditing({...editing,name_en:v})}/><div className="grid grid-cols-2 gap-4"><Num label="عدد التوكن" value={editing.tokens} onChange={v=>setEditing({...editing,tokens:v})}/><Num label="البونص" value={editing.bonus} onChange={v=>setEditing({...editing,bonus:v})}/><Num label="السعر العادي (د.م)" value={editing.price_mad} step="0.01" onChange={v=>setEditing({...editing,price_mad:v})}/><Num label="سعر العرض (اختياري)" value={editing.promo_price_mad??0} step="0.01" onChange={v=>setEditing({...editing,promo_price_mad:v||null})}/><Num label="الترتيب" value={editing.sort} onChange={v=>setEditing({...editing,sort:v})}/><label className="text-xs font-semibold text-ink/60">نهاية العرض<input type="datetime-local" dir="ltr" value={editing.promo_ends_at?editing.promo_ends_at.slice(0,16):""} onChange={e=>setEditing({...editing,promo_ends_at:e.target.value?new Date(e.target.value).toISOString():null})} className="mt-1.5 w-full rounded-xl border border-ink/12 bg-white px-3 py-2.5 text-sm"/></label></div><div className="grid grid-cols-2 gap-3"><Toggle label="الباقة مفعّلة" checked={editing.active} onChange={v=>setEditing({...editing,active:v})}/><Toggle label="الأكثر شيوعًا" checked={editing.popular} onChange={v=>setEditing({...editing,popular:v})} icon/></div></div><div className="sticky bottom-0 mt-7 flex justify-end gap-2 border-t border-ink/8 bg-paper/90 py-4"><Btn tone="ghost" onClick={()=>setEditing(null)}>إلغاء</Btn><Btn disabled={saving} onClick={save}><Save className="size-4"/>{saving?"جارٍ الحفظ…":"حفظ الباقة"}</Btn></div></div></div>}
 </div>}
function Field({label,value,onChange,dir}:{label:string;value:string;onChange:(v:string)=>void;dir?:"ltr"}){return <label className="block text-xs font-semibold text-ink/60">{label}<input dir={dir} value={value} onChange={e=>onChange(e.target.value)} className="mt-1.5 w-full rounded-xl border border-ink/12 bg-white px-3 py-2.5 text-sm outline-none focus:border-brand-teal"/></label>}
function Num({label,value,onChange,step="1"}:{label:string;value:number;onChange:(v:number)=>void;step?:string}){return <label className="text-xs font-semibold text-ink/60">{label}<input type="number" min="0" step={step} dir="ltr" value={value} onChange={e=>onChange(Number(e.target.value)||0)} className="mt-1.5 w-full rounded-xl border border-ink/12 bg-white px-3 py-2.5 text-sm"/></label>}
function Toggle({label,checked,onChange,icon}:{label:string;checked:boolean;onChange:(v:boolean)=>void;icon?:boolean}){return <button onClick={()=>onChange(!checked)} className={`flex items-center gap-2 rounded-xl border p-3 text-xs font-semibold ${checked?"border-brand-teal bg-brand-teal/8 text-brand-teal":"border-ink/10 bg-white text-ink/45"}`}>{icon&&<Star className="size-3.5"/>}<span className={`size-2 rounded-full ${checked?"bg-brand-teal":"bg-ink/20"}`}/>{label}</button>}
