import { useEffect,useRef,useState,type FormEvent } from "react";
import { useNavigate } from "@tanstack/react-router";
import { ArrowUpRight,Loader2,MessageSquareText,Search,X } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { useLocale } from "@/i18n/use-locale";

type Result={slug:string;title:string;excerpt:string;category_name:string;answers_count:number;views:number};
export function HeaderSearch(){
 const locale=useLocale();const navigate=useNavigate();const[query,setQuery]=useState("");const[results,setResults]=useState<Result[]>([]);const[loading,setLoading]=useState(false);const[focused,setFocused]=useState(false);const[mobile,setMobile]=useState(false);const request=useRef(0);
 const words=locale==="ar"?{placeholder:"ابحث عن سؤال أو موضوع…",empty:"لا توجد أسئلة مشابهة",hint:"اكتب حرفين على الأقل"}:locale==="fr"?{placeholder:"Rechercher une question…",empty:"Aucune question similaire",hint:"Saisissez au moins deux caractères"}:{placeholder:"Search questions and topics…",empty:"No similar questions",hint:"Type at least two characters"};
 useEffect(()=>{const q=query.trim();if(q.length<2){setResults([]);setLoading(false);return}const id=++request.current;setLoading(true);const timer=window.setTimeout(async()=>{const{data}=await supabase.rpc("search_public_questions",{p_query:q,p_limit:8});if(id===request.current){setResults((data as Result[])??[]);setLoading(false)}},220);return()=>window.clearTimeout(timer)},[query]);
 function openResult(item:Result){setFocused(false);setMobile(false);setQuery("");navigate({to:"/questions/$questionId",params:{questionId:item.slug}})}
 function submit(e:FormEvent){e.preventDefault();if(results[0])openResult(results[0]);else if(query.trim())navigate({to:"/questions",search:{}})}
 const panel=query.trim().length>=2&&focused?<div className="absolute inset-x-0 top-[calc(100%+.55rem)] z-[80] overflow-hidden rounded-2xl border border-border/60 bg-popover shadow-2xl"><div className="max-h-[28rem] overflow-y-auto p-2">{loading?<div className="flex items-center justify-center gap-2 py-10 text-sm text-muted-foreground"><Loader2 className="size-4 animate-spin"/>{locale==="ar"?"جارٍ البحث…":"Searching…"}</div>:results.length?results.map(item=><button key={item.slug} onMouseDown={e=>e.preventDefault()} onClick={()=>openResult(item)} className="group flex w-full gap-3 rounded-xl p-3 text-start transition hover:bg-muted"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary/8 text-primary"><MessageSquareText className="size-4"/></span><span className="min-w-0 flex-1"><span className="line-clamp-1 text-sm font-semibold group-hover:text-primary">{item.title}</span><span className="mt-1 line-clamp-1 text-[11px] text-muted-foreground">{item.excerpt}</span><span className="mt-1.5 flex gap-2 text-[9px] text-muted-foreground/70"><span>{item.category_name}</span><span>·</span><span>{item.answers_count} {locale==="ar"?"إجابة":"answers"}</span></span></span><ArrowUpRight className="mt-1 size-3.5 shrink-0 text-muted-foreground opacity-0 transition group-hover:opacity-100"/></button>):<div className="py-10 text-center text-sm text-muted-foreground">{words.empty}</div>}</div></div>:null;
 const form=<form onSubmit={submit} className="relative"><Search className="pointer-events-none absolute start-3.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} onFocus={()=>setFocused(true)} onBlur={()=>window.setTimeout(()=>setFocused(false),160)} placeholder={words.placeholder} className="h-11 w-full rounded-2xl border border-border/60 bg-background/75 pe-10 ps-10 text-sm shadow-sm outline-none backdrop-blur transition placeholder:text-muted-foreground/65 focus:border-primary/30 focus:ring-4 focus:ring-primary/8"/>{query&&<button type="button" onClick={()=>{setQuery("");setResults([])}} className="absolute end-3 top-1/2 -translate-y-1/2 rounded-lg p-1 text-muted-foreground hover:bg-muted"><X className="size-3.5"/></button>}{panel}</form>;
 return <><div className="mx-auto hidden w-full max-w-xl px-3 lg:block">{form}</div><button onClick={()=>{setMobile(true);setTimeout(()=>setFocused(true),0)}} className="grid size-10 place-items-center rounded-xl border border-border/50 bg-background/55 text-muted-foreground shadow-sm lg:hidden" aria-label={words.placeholder}><Search className="size-4"/></button>{mobile&&<div className="fixed inset-0 z-[90] bg-background/95 p-4 pt-[max(1rem,env(safe-area-inset-top))] backdrop-blur-2xl lg:hidden"><div className="mx-auto max-w-xl"><div className="mb-4 flex items-center justify-between"><p className="font-semibold">{words.placeholder}</p><button onClick={()=>{setMobile(false);setFocused(false)}} className="rounded-xl bg-muted p-2"><X className="size-5"/></button></div>{form}<p className="mt-3 text-center text-[10px] text-muted-foreground">{words.hint}</p></div></div>}</>;
}
