import { useRef } from "react";
import { Bold,Italic,Underline,List,ListOrdered,Link2,Paperclip,FileText,Image as ImageIcon,X } from "lucide-react";
import { Textarea } from "@/components/ui/textarea";

type Props={value:string;onChange:(value:string)=>void;placeholder:string;files:File[];onFiles:(files:File[])=>void;maxLength?:number};
export function QuestionComposer({value,onChange,placeholder,files,onFiles,maxLength=4000}:Props){
 const ref=useRef<HTMLTextAreaElement>(null);const input=useRef<HTMLInputElement>(null);
 function wrap(before:string,after=before,fallback="text"){const el=ref.current;if(!el)return;const start=el.selectionStart,end=el.selectionEnd;const selected=value.slice(start,end)||fallback;const next=value.slice(0,start)+before+selected+after+value.slice(end);onChange(next);requestAnimationFrame(()=>{el.focus();el.setSelectionRange(start+before.length,start+before.length+selected.length)})}
 function prefix(mark:string){const el=ref.current;if(!el)return;const start=value.lastIndexOf("\n",el.selectionStart-1)+1;onChange(value.slice(0,start)+mark+value.slice(start));requestAnimationFrame(()=>el.focus())}
 function addFiles(list:FileList|null){if(!list)return;const allowed=["image/jpeg","image/png","image/webp","application/pdf","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document"];const next=[...files];for(const file of Array.from(list)){if(next.length>=5)break;if(file.size<=10*1024*1024&&allowed.includes(file.type)&&!next.some(x=>x.name===file.name&&x.size===file.size))next.push(file)}onFiles(next);if(input.current)input.current.value=""}
 const tools=[{label:"Bold",icon:Bold,run:()=>wrap("**","**","important text")},{label:"Italic",icon:Italic,run:()=>wrap("*","*","emphasis")},{label:"Underline",icon:Underline,run:()=>wrap("__","__","underlined text")},{label:"Bullets",icon:List,run:()=>prefix("- ")},{label:"Numbered",icon:ListOrdered,run:()=>prefix("1. ")},{label:"Link",icon:Link2,run:()=>wrap("[","](https://)","link title")}];
 return <div className="overflow-hidden rounded-2xl border border-border/70 bg-background transition focus-within:border-primary/35 focus-within:ring-4 focus-within:ring-primary/8"><div className="flex flex-wrap items-center gap-1 border-b border-border/60 bg-muted/35 p-2">{tools.map(tool=><button key={tool.label} type="button" title={tool.label} onClick={tool.run} className="grid size-8 place-items-center rounded-lg text-muted-foreground transition hover:bg-background hover:text-primary hover:shadow-sm"><tool.icon className="size-4"/></button>)}<span className="mx-1 h-5 w-px bg-border"/><button type="button" onClick={()=>input.current?.click()} className="inline-flex h-8 items-center gap-1.5 rounded-lg px-2.5 text-xs font-semibold text-muted-foreground transition hover:bg-background hover:text-primary hover:shadow-sm"><Paperclip className="size-4"/> Attach</button><input ref={input} type="file" multiple hidden accept="image/jpeg,image/png,image/webp,.pdf,.doc,.docx" onChange={e=>addFiles(e.target.files)}/><span className="ms-auto px-2 text-[10px] text-muted-foreground">{value.length}/{maxLength}</span></div><Textarea ref={ref} value={value} maxLength={maxLength} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="min-h-52 resize-y rounded-none border-0 bg-transparent shadow-none focus-visible:ring-0"/>{files.length>0&&<div className="grid gap-2 border-t border-border/60 bg-muted/20 p-3 sm:grid-cols-2">{files.map((file,index)=><div key={`${file.name}-${file.size}`} className="flex items-center gap-2 rounded-xl border border-border/60 bg-background p-2.5"><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-primary/8 text-primary">{file.type.startsWith("image/")?<ImageIcon className="size-4"/>:<FileText className="size-4"/>}</span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold">{file.name}</span><span className="text-[9px] text-muted-foreground">{(file.size/1024/1024).toFixed(2)} MB</span></span><button type="button" onClick={()=>onFiles(files.filter((_,i)=>i!==index))} className="rounded-lg p-1.5 text-muted-foreground hover:bg-destructive/8 hover:text-destructive"><X className="size-3.5"/></button></div>)}</div>}</div>;
}

export function RichTextContent({text,className=""}:{text:string;className?:string}){
 function inline(line:string){const parts=line.split(/(\*\*.*?\*\*|__.*?__|\*.*?\*|\[[^\]]+\]\(https?:\/\/[^)]+\))/g);return parts.map((part,index)=>{if(/^\*\*.*\*\*$/.test(part))return <strong key={index}>{part.slice(2,-2)}</strong>;if(/^__.*__$/.test(part))return <u key={index}>{part.slice(2,-2)}</u>;if(/^\*.*\*$/.test(part))return <em key={index}>{part.slice(1,-1)}</em>;const link=part.match(/^\[([^\]]+)\]\((https?:\/\/[^)]+)\)$/);if(link)return <a key={index} href={link[2]} target="_blank" rel="noreferrer" className="font-medium text-primary underline">{link[1]}</a>;return <span key={index}>{part}</span>})}
 const lines=text.split("\n");return <div className={`space-y-2 ${className}`}>{lines.map((line,index)=>{if(line.startsWith("- "))return <div key={index} className="flex gap-2"><span className="mt-3 size-1.5 shrink-0 rounded-full bg-secondary"/><span>{inline(line.slice(2))}</span></div>;const numbered=line.match(/^\d+\.\s+(.*)/);if(numbered)return <div key={index} className="flex gap-2"><span className="font-semibold text-secondary">{line.match(/^\d+/)?.[0]}.</span><span>{inline(numbered[1])}</span></div>;return line?<p key={index}>{inline(line)}</p>:<div key={index} className="h-2"/>})}</div>;
}
