/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ExpertsIndexRouteImport } from './routes/experts.index'
import { Route as ExpertsExpertSlugRouteImport } from './routes/experts.$expertSlug'
import { Route as QuestionsIndexRouteImport } from './routes/questions.index'
import { Route as QuestionsQuestionIdRouteImport } from './routes/questions.$questionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsIndexRoute = ExpertsIndexRouteImport.update({
  id: '/experts/',
  path: '/experts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsExpertSlugRoute = ExpertsExpertSlugRouteImport.update({
  id: '/experts/$expertSlug',
  path: '/experts/$expertSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIndexRoute = QuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsQuestionIdRoute = QuestionsQuestionIdRouteImport.update({
  id: '/questions/$questionId',
  path: '/questions/$questionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/experts/$expertSlug': typeof ExpertsExpertSlugRoute
  '/questions/$questionId': typeof QuestionsQuestionIdRoute
  '/experts/': typeof ExpertsIndexRoute
  '/questions/': typeof QuestionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/experts/$expertSlug': typeof ExpertsExpertSlugRoute
  '/questions/$questionId': typeof QuestionsQuestionIdRoute
  '/experts': typeof ExpertsIndexRoute
  '/questions': typeof QuestionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/experts/$expertSlug': typeof ExpertsExpertSlugRoute
  '/questions/$questionId': typeof QuestionsQuestionIdRoute
  '/experts/': typeof ExpertsIndexRoute
  '/questions/': typeof QuestionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/experts/$expertSlug'
    | '/questions/$questionId'
    | '/experts/'
    | '/questions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/experts/$expertSlug'
    | '/questions/$questionId'
    | '/experts'
    | '/questions'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/experts/$expertSlug'
    | '/questions/$questionId'
    | '/experts/'
    | '/questions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  ExpertsExpertSlugRoute: typeof ExpertsExpertSlugRoute
  QuestionsQuestionIdRoute: typeof QuestionsQuestionIdRoute
  ExpertsIndexRoute: typeof ExpertsIndexRoute
  QuestionsIndexRoute: typeof QuestionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts/': {
      id: '/experts/'
      path: '/experts'
      fullPath: '/experts/'
      preLoaderRoute: typeof ExpertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts/$expertSlug': {
      id: '/experts/$expertSlug'
      path: '/experts/$expertSlug'
      fullPath: '/experts/$expertSlug'
      preLoaderRoute: typeof ExpertsExpertSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/': {
      id: '/questions/'
      path: '/questions'
      fullPath: '/questions/'
      preLoaderRoute: typeof QuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/$questionId': {
      id: '/questions/$questionId'
      path: '/questions/$questionId'
      fullPath: '/questions/$questionId'
      preLoaderRoute: typeof QuestionsQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  ExpertsExpertSlugRoute: ExpertsExpertSlugRoute,
  QuestionsQuestionIdRoute: QuestionsQuestionIdRoute,
  ExpertsIndexRoute: ExpertsIndexRoute,
  QuestionsIndexRoute: QuestionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
